### PR TITLE
API - Control hardcoded clipToBounds() modifier

### PR DESCRIPTION
**Pull request by GIGAMOLE**
First, I like this library, great job. Second, I saw that you added [this feature](https://github.com/onebone/compose-collapsing-toolbar/issues/12) to the **v3** milestone, but it's already 2 years without any progress. Please, merge it so I can use your library as a remote dependency, rather than a locally changed module.

### CODE REVIEW

**Comment by GIGAMOLE** [comment]
By the way, who wants to use this feature, I created a separated remote dependency, while this PR is under review:

Add it in your root build.gradle at the end of repositories:

```groovy
all projects {
	repositories {
		...
		maven { url 'https://jitpack.io' }
	}
}
```

Step 2. Add the dependency

```groovy
dependencies {
        implementation 'com.github.GIGAMOLE:ComposeCollapsingToolbar:latest-version'
}
```

Or you can simply download it from there:

https://github.com/GIGAMOLE/ComposeCollapsingToolbar/releases

**Comment by onebone** [comment]
Rather than changing the existing behavior, I think it is better to put an optional parameter `clip` with default value `true` (to maintain the current default behavior). How do you feel about it?

**Comment by GIGAMOLE** [comment]
In terms of interoperability - yes. Let me redefine it, by introducing an optional `clip` param.

**Comment by GIGAMOLE** [comment]
Done.

**Comment by onebone** [comment]
Looks good!

**Pull request merged**
